-- Make the audit hash-chain order deterministic. created_at has only millisecond
-- precision, so rapid same-ms writes tie and ORDER BY created_at is not a stable total
-- order — which can pick the wrong previous row for the hash chain. A monotonic sequence
-- gives a strict, gap-tolerant insertion order that the writer and verifier both use.
ALTER TABLE audit_logs ADD COLUMN seq bigint GENERATED BY DEFAULT AS IDENTITY;
CREATE UNIQUE INDEX ix_audit_logs_seq ON audit_logs(seq);
