-- Catalog: M365 offboard + security/outage report request types. Idempotent upserts
-- (ON CONFLICT key) so this is safe whether or not an item was already seeded.
-- owning_tier routes to a seeded assignment group by exact name.
INSERT INTO service_catalog_items
  (key, name, category, description, ticket_type, owning_tier, escalates_to,
   requires_approval, approver_hint, default_priority, security_class,
   sla_response_min, sla_resolution_min, fulfillment_steps, active)
VALUES
  ('m365.offboard',
   'M365 — Offboard departing user',
   'Identity',
   'Disable a departing user''s Microsoft 365 identity, preserve required data, release license consumption, and schedule account deletion per retention policy. Response within 2 business hours (15 minutes for Involuntary / Security Incident). Capture: full name, last day, hard-delete date, and evidence (license snapshot, group membership diff, hold confirmation, device disposition, approver of record).',
   'service_request', 'Tier 2 — M365 Administrator', 'Security Operations',
   true, 'Manager / HR (+ SecOps if involuntary)', 'P2', 'security', 120, 480,
   '[{"key":"triage","label":"Verify authorization & offboard type (voluntary / involuntary / security)","role":"Tier1","automatable":false},
     {"key":"approval","label":"Manager / HR approval (approver of record)","role":"OrgAdmin","automatable":false},
     {"key":"disable","label":"Disable identity, revoke sessions & tokens, reset password","role":"Tier2","automatable":true},
     {"key":"preserve","label":"Apply legal hold; preserve mailbox + OneDrive (hold confirmation)","role":"SecurityAnalyst","automatable":false},
     {"key":"groups","label":"Capture group membership diff; remove group & admin role memberships","role":"Tier2","automatable":true},
     {"key":"license","label":"Capture license snapshot; reclaim license consumption","role":"Tier2","automatable":true},
     {"key":"device","label":"Device disposition — retrieve / wipe / reassign","role":"Tier2","automatable":false},
     {"key":"schedule_delete","label":"Schedule account hard-delete per retention policy","role":"Tier2","automatable":true},
     {"key":"evidence","label":"Record evidence bundle (license snapshot, group diff, hold, device, approver)","role":"Tier2","automatable":false}]'::jsonb,
   true),

  ('security.phishing_report',
   'Report suspected phishing',
   'Security',
   'Report an unsolicited or suspicious email. Triaged by Security Operations within 15 minutes, 24x7. Do not forward the email — attach it as .eml or .msg.',
   'incident', 'Security Operations', NULL,
   false, NULL, 'P2', 'security', 15, 240,
   '[{"key":"triage","label":"SecOps triage of reported message","role":"SecurityAnalyst","automatable":false},
     {"key":"analyze","label":"Analyze headers/URLs/attachments (detonate as needed)","role":"SecurityAnalyst","automatable":true},
     {"key":"contain","label":"Block sender/URLs; purge similar messages tenant-wide","role":"SecurityAnalyst","automatable":true},
     {"key":"notify","label":"Notify reporter and affected users","role":"SecurityAnalyst","automatable":false}]'::jsonb,
   true),

  ('security.incident_report',
   'Report a security incident',
   'Security',
   'Report a suspected compromise, lost device, or data exposure. First response within 15 minutes, 24x7. Paged to Security Operations.',
   'incident', 'Security Operations', NULL,
   false, NULL, 'P1', 'security', 15, 240,
   '[{"key":"triage","label":"SecOps triage and page on-call","role":"SecurityAnalyst","automatable":false},
     {"key":"contain","label":"Contain — isolate accounts/devices, revoke access","role":"SecurityAnalyst","automatable":false},
     {"key":"investigate","label":"Investigate scope, root cause, and data exposure","role":"SecurityAnalyst","automatable":false},
     {"key":"recover","label":"Eradicate and recover affected systems","role":"Tier3","automatable":false},
     {"key":"notify","label":"Notify stakeholders; meet regulatory obligations","role":"SecurityAnalyst","automatable":false},
     {"key":"review","label":"Post-incident review and lessons learned","role":"SecurityAnalyst","automatable":false}]'::jsonb,
   true),

  ('ops.service_outage',
   'Report a service outage',
   'Incident',
   'Report that a production service is down or degraded for multiple users. First response within 15 minutes, 24x7.',
   'incident', 'Tier 1 — Helpdesk Analyst', 'Tier 3 — Cloud Operations',
   false, NULL, 'P1', 'standard', 15, 240,
   '[{"key":"triage","label":"Confirm scope, impact, and affected service","role":"Tier1","automatable":false},
     {"key":"declare","label":"Declare major incident; page on-call if warranted","role":"Tier1","automatable":false},
     {"key":"mitigate","label":"Mitigate / restore service","role":"Tier3","automatable":false},
     {"key":"comms","label":"Post status updates to affected customers","role":"Tier2","automatable":false},
     {"key":"resolve","label":"Confirm resolution with reporters","role":"Tier1","automatable":false},
     {"key":"review","label":"Major-incident review","role":"Tier3","automatable":false}]'::jsonb,
   true)
ON CONFLICT (key) DO UPDATE SET
  name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description,
  ticket_type = EXCLUDED.ticket_type, owning_tier = EXCLUDED.owning_tier, escalates_to = EXCLUDED.escalates_to,
  requires_approval = EXCLUDED.requires_approval, approver_hint = EXCLUDED.approver_hint,
  default_priority = EXCLUDED.default_priority, security_class = EXCLUDED.security_class,
  sla_response_min = EXCLUDED.sla_response_min, sla_resolution_min = EXCLUDED.sla_resolution_min,
  fulfillment_steps = EXCLUDED.fulfillment_steps, active = true;
